#!/bin/bash
set -e
# Authors:      Rodrigo Cuadra
#               with Collaboration of Jose Miguel Rivera
#
# Support:      rcuadra@aplitel.com
#
host_active=`pcs status | awk '/virtual_ip/ {print $4}'`
host_master=`pcs status | awk '/Online/ {print $3}'`
host_slave=`pcs status | awk '/Online/ {print $4}'`

        if [ "$host_master" = "$host_active" ] ;then
		host_pasive=$host_slave
	else
		host_pasive=$host_master
	fi

        if [ "$host_master" = "" ] ;then
		echo -e "There are problems with high availability, please check with the command "pcs status" (we recommend applying the command "pcs cluster unstandby" in both servers)"
		exit;
	fi

        if [ "$host_slave" = "" ] ;then
                echo -e "There are problems with high availability, please check with the command "pcs status" (we recommend applying the command "pcs cluster unstandby" in both servers)"
                exit;
        fi

echo -e "************************************************************"
echo -e "*     Change the roles of servers in high availability     *"
echo -e "*\e[41m WARNING-WARNING-WARNING-WARNING-WARNING-WARNING-WARNING  \e[0m*"
echo -e "*All calls in progress will be lost and the system will be *"
echo -e "*     be in an unavailable state for a few seconds.        *"
echo -e "************************************************************"
	while [[ $veryfy_bascul != yes && $veryfy_bascul != no ]]
	do
		read -p "Are you sure to switch from $host_active to $host_pasive? (yes,no) > " veryfy_bascul 
	done
	if [ "$veryfy_bascul" = "yes" ] ;then
                BAR='........................................................'
                i=0
		pcs cluster unstandby $host_active
		pcs cluster unstandby $host_pasive
		pcs cluster standby $host_active
		host_master_new=$host_active
		echo -e "Stopping services on " $host_active
		while [[ $host_active == $host_master_new ]]
		do
                        let i=i+1
                        echo -ne "\r${BAR:0:$i}"
			sleep 1
			host_master_new=`pcs status resources | awk '/virtual_ip/ {print $4}'`
		done
                echo -e "Done"
                echo -e "Starting services on " $host_pasive

		virtualip=`pcs status resources | awk '/virtual_ip/ {print $3}'`
               	i=0
        	while [ $virtualip != 'Started' ] && [ $i -lt 10 ]
        	do
			let i=i+1
                        echo -ne "\r${BAR:0:$i}"
			sleep 1
                	virtualip=`pcs status resources | awk '/virtual_ip/ {print $3}'`
        	done
		if [ $i -lt 10 ]
		then
			echo -e "Virtual IP: Started on " $host_pasive
			echo -e "Done"
		else
			echo -e "Virtual IP: Fail to Start on " $host_pasive
			echo -e "Fail"		
		fi

		lsyncd=`pcs status resources | awk '/lsyncd/ {print $3}'`
		i=0
        	while [ $lsyncd != 'Started' ] && [ $i -lt 10 ]
        	do
			let i=i+1
                        echo -ne "\r${BAR:0:$i}"
			sleep 1
                	lsyncd=`pcs status resources | awk '/lsyncd/ {print $3}'`
        	done
		if [ $i -lt 10 ]
		then
			echo -e "Lsyncd: Started on " $host_pasive
			echo -e "Done"
		else
			echo -e "Lsyncd: Fail to Start on " $host_pasive
			echo -e "Fail"		
		fi

		asterisk=`pcs status resources | awk '/asterisk/ {print $3}'`
		i=0
        	while [ $asterisk != 'Started' ] && [ $i -lt 10 ]
        	do
			let i=i+1
                        echo -ne "\r${BAR:0:$i}"
			sleep 1
                	asterisk=`pcs status resources | awk '/asterisk/ {print $3}'`
        	done
		if [ $i -lt 10 ]
		then
			echo -e "Asterisk: Started on " $host_pasive
			echo -e "Done"
		else
			echo -e "Asterisk: Fail to Start on " $host_pasive
			echo -e "Fail"		
		fi

		pcs cluster unstandby $host_active
		sleep 3
		echo -e "Done,"
		pcs status
	else
		echo -e "Nothing to do, bye, bye"
	fi
